# app/engine/flags.py
"""Deterministic Tier-4 flags — every quote lists its assumptions and
blockers. No LLM involved; see select-windows-domain-brief.md."""

from dataclasses import dataclass

from app.engine.config_codes import parse_config_code
from app.engine.enrich import EnrichmentResult

AR_FLAG_MESSAGE = "AR measurement ±20mm — site check measure required before ordering"
ASBESTOS_FLAG_MESSAGE = "SELECT WILL NOT REMOVE — client clearance certificate required; blocks scheduling"
MULTI_READING_DIMENSION_MESSAGE_SUFFIX = (
    "one or more dimensions resolved to the minimum of readings that disagreed within "
    "tolerance (≤15%) — confirm exact measurement on site before ordering"
)

# sliding/bi_fold are shared between window_types and door_types in the
# taxonomy — product_type alone can't tell them apart. When a config_code is
# present, its letter-prefix DOES distinguish them (SL=sliding window vs
# SD=sliding door, BFW vs BFD) — see _item_is_door below. Only without a
# config_code do we fall back to this over-inclusive set, on the same
# reasoning as before: under-flagging a real door is the worse failure mode.
DOOR_PRODUCT_TYPES = {"sliding", "stacking", "bi_fold", "hinged", "cedar_entry"}
MIN_SAFETY_GLASS_SILL_MM = 500


def _item_is_door(item) -> bool:
    config_code = getattr(item, "config_code", None)
    if config_code:
        category = parse_config_code(config_code).category
        if category != "unknown":
            return category == "door"
    return item.product_type in DOOR_PRODUCT_TYPES


@dataclass
class Flag:
    code: str
    message: str


def ar_measurement_flags(items) -> list[Flag]:
    for item in items:
        readings = list(item.height_readings) + list(item.width_readings)
        if any(r.source == "ar_overlay" for r in readings):
            return [Flag(code="ar_measurement", message=AR_FLAG_MESSAGE)]
    return []


def asbestos_flags(installation) -> list[Flag]:
    if installation is not None and installation.asbestos == "yes":
        return [Flag(code="asbestos", message=ASBESTOS_FLAG_MESSAGE)]
    return []


def safety_glass_flags(items, sill_height_mm: dict[int, int] | None = None) -> list[Flag]:
    sill_height_mm = sill_height_mm or {}
    flags = []
    for item in items:
        is_door = _item_is_door(item)
        sill = sill_height_mm.get(item.item_no)
        low_sill = sill is not None and sill < MIN_SAFETY_GLASS_SILL_MM
        if is_door or low_sill:
            flags.append(
                Flag(
                    code="as1288_safety_glass",
                    message=f"Item {item.item_no}: AS1288 Grade A safety glass mandatory",
                )
            )
    return flags


def multi_reading_dimension_flags(items) -> list[Flag]:
    flags = []
    for item in items:
        if getattr(item, "dimensions_multi_reading", False):
            flags.append(
                Flag(
                    code="dimensions_multi_reading",
                    message=f"Item {item.item_no}: {MULTI_READING_DIMENSION_MESSAGE_SUFFIX}",
                )
            )
    return flags


def default_enrichment_flags(items_with_enrichment: list[tuple[int, EnrichmentResult]]) -> list[Flag]:
    flags = []
    for item_no, enrichment in items_with_enrichment:
        if enrichment.source == "owner_edit":
            # Anthony's own correction (app/api/owner_quotes.py's edit
            # endpoint) — the highest-trust source there is, so unlike the
            # llm_estimate/default_spec branches below it needs no
            # "unverified" disclaimer.
            continue
        if enrichment.source == "llm_estimate":
            flags.append(
                Flag(
                    code="llm_material_estimate",
                    message=(
                        f"Item {item_no}: AI ESTIMATE — materials/spec generated by AI, "
                        f"not verified, pending RAG-backed data"
                    ),
                )
            )
            continue
        note = " (unrecognized product/material — verify manually)" if enrichment.unrecognized else ""
        flags.append(
            Flag(
                code="default_spec",
                message=(
                    f"Item {item_no}: glass/hardware/labour spec is a DEFAULT placeholder, "
                    f"not extracted{note}"
                ),
            )
        )
    return flags


# Points subtracted per flag instance when scoring how much of Anthony's
# time a quote likely needs (see compute_readiness_score below) — one Flag
# object already exists per affected item, so severity scales naturally
# with how many items are affected, not just whether a flag type is present
# at all.
_READINESS_PENALTIES: dict[str, int] = {
    "asbestos": 30,
    "ar_measurement": 10,
    "dimensions_multi_reading": 10,
    "as1288_safety_glass": 5,
    "llm_material_estimate": 5,
    "default_spec": 10,
}


def compute_readiness_score(flags: list[Flag]) -> int:
    """Deterministic baseline for how much of Anthony's time a quote likely
    needs — higher means less scrutiny required. Deliberately NOT an LLM
    output: asking a model to invent a calibrated 0-100 number is a known
    weak spot (the same quote could score differently run to run), which
    matters for something meant to guide real review time. Combined with
    the learning agent's lesson-match result in
    app/workers/pipeline.py::_run_approval_agent_check for the final score
    stored on Quote.readiness_score — the one genuinely AI-driven input."""
    score = 100
    for flag in flags:
        score -= _READINESS_PENALTIES.get(flag.code, 0)
    return max(0, min(100, score))


def build_flags(
    items,
    installation,
    items_with_enrichment: list[tuple[int, EnrichmentResult]],
    sill_height_mm: dict[int, int] | None = None,
) -> list[Flag]:
    return [
        *ar_measurement_flags(items),
        *asbestos_flags(installation),
        *safety_glass_flags(items, sill_height_mm),
        *multi_reading_dimension_flags(items),
        *default_enrichment_flags(items_with_enrichment),
    ]
