import { StyleSheet } from "react-native";

export const colors = {
  ink: "#1c232b",
  steel: "#5f6d78",
  line: "#dbdfdb",
  paper: "#f5f6f4",
  card: "#ffffff",
  accent: "#2f6f7e",
  accentSoft: "#e4eeee",
  warn: "#a85e0f",
  warnSoft: "#faf1e3",
  danger: "#b3261e",
  dangerSoft: "#fbeceb",
};

export const shared = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.paper },
  scrollContent: { padding: 20, gap: 16 },
  h1: { fontSize: 22, fontWeight: "700", color: colors.ink },
  h2: { fontSize: 13, fontWeight: "700", color: colors.steel, textTransform: "uppercase", letterSpacing: 0.5 },
  card: {
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    gap: 12,
  },
  label: { fontSize: 12, color: colors.steel, marginBottom: 4 },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
    backgroundColor: colors.card,
  },
  row: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  buttonSecondary: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonSecondaryText: { color: colors.accent, fontWeight: "700", fontSize: 15 },
  chip: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  chipSelected: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  chipText: { color: colors.ink, fontSize: 13 },
  chipTextSelected: { color: colors.accent, fontWeight: "700" },
  errorText: { color: colors.danger, fontSize: 13 },
  muted: { color: colors.steel, fontSize: 13 },
});
